server:
  port: 8081

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/name?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false"
    username: "root"
    password: XCC18535507996