spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/webchat?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: XCC18535507996

  redis:
    password: XCC18535507996
    host: 127.0.0.1
    port: 6379
    connect-timeout: 3000
    database: 0

