spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/web-chat?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: hrn77799.

  redis:
    host: 127.0.0.1
    port: 6379
    connect-timeout: 3000
    database: 0